### ISSUE TITLE
Feature: Compare multiple packages on a single chart

### ISSUE THREAD

**Issue by alexeyinkin** [Rexios80/pub_stats#1]
Often we need to see how a package is performing against similar ones over time.

There are also official uses for that. It could be to get funding from the parent company, or to apply for talent immigration program, or anything else. Sure we can look at separate charts, but there are always people in authority who will act on a single chart from a proven source but will not trust a chart I compile myself, and will not bother reading explanation of multiple charts.

Also, this is just fun.

As a bonus, if this is implemented, FlutterGems may be interested in building charts for each category, and you can get traffic from them.

**Comment by alexeyinkin** [comment]
I think Google Trends is a great example of the good UI to select multiple things and put them on a single chart. They even have clean and readable URLs when doing so.

**Comment by Rexios80** [comment]
How's this?

https://beta.pubstats.dev/#/packages/flutter_bloc?compare=riverpod

**Comment by alexeyinkin** [comment]
The URL of `flutter_bloc?compare=riverpod` puts one package as the main one and the other as secondary. The problem is, to someone viewing this page it is not clear how to add a 3rd package.

If the URL was this:
`https://beta.pubstats.dev/#/packages/flutter_bloc,riverpod`
they could just append `,third_package`

For reference, see the URLs in Google Trends:
https://trends.google.com/trends/explore?date=now%201-d&geo=GE&q=flutter,react%20native&hl=en

Also, there is `riverpod (x)` button to remove only one of the two packages. I think if viewing more than one package, the delete buttons should be for all packages: `flutter_bloc (x) | riverpod (x)`

These two changes will make the page more symmetric, and symmetry always pays when things develop further.

Also, I see some wrong data with riverpod showing 84% popularity while it is 98% in reality.

**Comment by Rexios80** [comment]
Popularity scores have been weird since the issues started. Things should normalize when that gets fixed. Data comes straight from the API.

I'm trying to make this work without making a whole new UI. I'll try to implement your suggestions.

**Comment by alexeyinkin** [comment]
I like the project. In December, I may spend a few days helping on this.

**Comment by Rexios80** [comment]
How is this?

https://beta.pubstats.dev/#/packages/flutter_bloc,riverpod

**Comment by alexeyinkin** [comment]
Awesome!
