### ISSUE TITLE
Refactor URL logic

### ISSUE THREAD

**Issue by alexeyinkin** [Rexios80/pub_stats#3]
Steps to reproduce:
1. Open any package stats: https://pubstats.dev/#/packages/cupertino_icons
2. Edit the URL in the address bar to change the package name
3. Press Enter

Expected: Navigated to the new package.
Actual: The URL change is reverted, still viewing the old package.

The problem is from not using Navigator 2.0, and because the URL is parsed only once in `DataController.create()` in `main()`.

**Comment by alexeyinkin** [comment]
This one I can fix if you approve my package for routing: https://pub.dev/packages/app_state

If you care about maintainability, the largest app it was used is Apache Beam Playground: https://play.beam.apache.org
Approved by their engineers, no problems so far.

**Comment by Rexios80** [comment]
I tried looking into this but gave up for now. Is it possible to have the navigation route update without actually pushing a new page? The entire app is actually just on one route.

**Comment by Rexios80** [comment]
Or is it possible to listen for URL changes outside of the router?

**Comment by alexeyinkin** [comment]
In theory, it is possible to listen to the URL change and do something instantly, and that is what Navigator 2.0 is all about. However, in my apps I have seen it reloading the app at the given URL, which is still better than reverting the change. I did not investigate further because reloading was OK for me.

**Comment by Rexios80** [comment]
I'm fine with the page reloading when the URL bar is manually changed, but what I don't want is the app to try and navigate between states when the route is updated by the UI

**Comment by alexeyinkin** [comment]
No, programmatic updates of the address bar do not cause reload with Navigator 2.0, just like it is the case now in the app.

**Comment by Rexios80** [comment]
What I'm saying is if we wanted to use the navigator to go from package1 to package2 and we did `Navigator.pushNamed('/packages/package2` would it be possible for that call to NOT actually navigate

**Comment by Rexios80** [comment]
This should be fixed on https://beta.pubstats.dev. Let me know if it works for you.

**Comment by Rexios80** [comment]
Hey the navigation buttons work too and all I had to do was bypass the Flutter Navigator entirely 🙃

**Comment by Rexios80** [comment]
Closing since this appears to work
