### ISSUE TITLE
Compare 2 (or more packages)

### ISSUE THREAD

**Issue by Tienisto** [Rexios80/pub_stats#6]
Thank you for this beautiful website!

I wish there would be an option to show the graph of 2 packages side by side similar to

https://star-history.com/#flutter/flutter&facebook/react-native&Date

This would be awesome!

**Comment by Rexios80** [comment]
https://pubstats.dev/#/packages/bloc,mobx

Just click the "Compare" button in the search suggestions

<img width="778" alt="Screenshot 2023-12-21 at 5 37 57 AM" src="https://github.com/Rexios80/pub_stats/assets/7896519/c31c04dd-51c6-401b-be3b-68633da05aa4">

**Comment by Rexios80** [comment]
If you have any more suggestions please let me know

**Comment by Tienisto** [comment]
Thanks! I didn't notice that
